[workspace]
members = ["cyper-core", "cyper"]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/compio-rs/cyper"

[workspace.dependencies]
compio = "0.12.0"
compio-quic = "0.1.0"
cyper-core = { path = "./cyper-core", default-features = false, version = "0.1.0" }

cfg-if = "1.0.0"
futures-channel = "0.3.29"
futures-util = "0.3.30"
send_wrapper = "0.6"

rustls = { version = "0.23.13", default-features = false }
rustls-platform-verifier = "0.3.4"

hyper = "1.4.1"
hyper-util = "0.1.8"
