[workspace]
members = ["cyper-tls", "cyper-util", "cyper-client"]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/compio-rs/cyper"

[workspace.dependencies]
compio-buf = "0.2.0-beta.1"
compio-driver = { version = "0.2.0-beta.1", features = ["io-uring", "polling"] }
compio-runtime = "0.2.0-beta.1"
compio-macros = "0.1.1-beta.1"
compio-io = "0.1.0-beta.1"
compio-net = "0.2.0-beta.1"
cyper-tls = { path = "./cyper-tls", version = "0.1.0" }
cyper-util = { path = "./cyper-util", version = "0.1.0" }

cfg-if = "1.0.0"
futures-channel = "0.3.29"
send_wrapper = "0.6"
tokio = "1.33.0"

native-tls = "0.2.11"
rustls = "0.22.0-alpha.4"
rustls-native-certs = "0.7.0-alpha.1"

hyper = "0.14"
