[package]
name = "cyper-core"
version = "0.1.0-beta.1"
description = "Core adaptors and services for compio running on hyper."
categories = ["asynchronous", "network-programming"]
keywords = ["async", "net"]
edition = { workspace = true }
authors = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
compio = { workspace = true, features = ["io-compat", "tls"] }

native-tls = { workspace = true, optional = true }
rustls = { workspace = true, optional = true }
rustls-native-certs = { workspace = true, optional = true }

cfg-if = { workspace = true }
hyper = { workspace = true }
send_wrapper = { workspace = true, features = ["futures"] }
tokio = { workspace = true }

[features]
default = ["native-tls"]
native-tls = ["compio/native-tls", "dep:native-tls"]
rustls = ["compio/rustls", "dep:rustls", "dep:rustls-native-certs"]
vendored = ["native-tls?/vendored"]

client = ["hyper/client"]
server = ["hyper/server"]

all = ["native-tls", "rustls", "client", "server"]

read_buf = ["compio/read_buf"]
nightly = ["read_buf", "compio/nightly"]
